version: '3.4'

services:
  rest-api:
    image: rest-api:dev
    container_name: RestAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RestAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_rest-api$
    volumes:
      - C:\fontes\Cursos\RestWithAspnet5\RestWithAspnet5\RestWithASPNET\RestAPI\RestAPI:/app
      - C:\fontes\Cursos\RestWithAspnet5\RestWithAspnet5\RestWithASPNET\RestAPI:/src
      - C:\Users\Osvaldo\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_rest-api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_rest-api$ \"/src/../02_Calculator/RestAPI/RestAPI/bin/Debug/net5.0/RestAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true